<?php

namespace Tests\Feature\Livewire\Account;

use App\Livewire\Account\Settings;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Livewire\Livewire;
use Tests\TestCase;

class EditTest extends TestCase
{

    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->withTokens()->create();
    }


    public function test_renders_successfully()
    {
        $tokens = $this->user->tokens;
        $testable = Livewire::actingAs($this->user, 'api')
            ->test(Settings::class);
        $testable->assertStatus(200);
        foreach ($tokens as $token){
            $testable->assertSeeText($token->name);
        }
    }
}
