<?php

namespace Tests\Feature\Livewire\Account\Tokens;

use App\Livewire\Account\Tokens\Table;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Livewire\Livewire;
use Tests\TestCase;

class TableTest extends TestCase
{
    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->withTokens(3)->create();
    }

    public function test_renders_successfully()
    {
        $testable = Livewire::actingAs($this->user, 'api')
            ->test(Table::class);
        $testable->assertStatus(200);
        $tokens = $this->user->tokens;
        $randomToken = $tokens->random();
        foreach ($tokens as $token){
            $testable->assertSeeText($token->name);
        }
        $testable->call('revokeToken', $randomToken->id);
        $testable->assertDontSeeText($randomToken->name);
    }
}
